type MaterialItem = { id: string; type: string; business: string; status: string; eta: string }
type RequestItem = { id: string; business: string; material: string; requestDate: string; status: string }
type Partner = { id: string; name: string; type: string; status: string }
type Certificate = { id: string; business: string; material: string; weightKg: number; date: string }

const STORAGE_KEY = 'midhori_demo_state'

const initialState = {
  materials: [
    { id: 'C-120', type: 'Cardboard', business: 'Green Supply Co.', status: 'In transit', eta: '2 hrs' },
    { id: 'M-333', type: 'Metal', business: 'City Foods', status: 'Delivered', eta: 'Completed' },
    { id: 'P-021', type: 'Plastic', business: 'EcoPack Ltd.', status: 'Awaiting pickup', eta: 'Today' },
  ] as MaterialItem[],
  requests: [
    { id: 'R-100', business: 'Eco Foods', material: 'Cardboard', requestDate: '2026-07-20', status: 'Pending' },
  ] as RequestItem[],
  partners: [
    { id: 'P-1', name: 'Green Cycle Recycling', type: 'Plastic', status: 'Active' },
  ] as Partner[],
  certificates: [
    { id: 'CERT-2026-001', business: 'EcoPack Ltd.', material: 'Plastic', weightKg: 2300, date: '2026-07-20' },
  ] as Certificate[],
}

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return structuredClone(initialState)
    return JSON.parse(raw)
  } catch (e) {
    return structuredClone(initialState)
  }
}

function saveState(state: any) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
}

export function getDemoState() {
  return loadState()
}

export function addSignupRequest(business: string, material: string) {
  const state = loadState()
  const id = 'R-' + Math.floor(100 + Math.random() * 900)
  state.requests.push({ id, business, material, requestDate: new Date().toISOString().slice(0, 10), status: 'Pending' })
  saveState(state)
  return id
}

export function approveRequest(requestId: string) {
  const state = loadState()
  const req = state.requests.find((r: RequestItem) => r.id === requestId)
  if (req) {
    req.status = 'Approved'
    const pid = 'P-' + Math.floor(1 + Math.random() * 999)
    state.partners.push({ id: pid, name: req.business + ' Partner', type: req.material, status: 'Active' })
    saveState(state)
  }
}

export function createCertificate(business: string, material: string, weightKg: number) {
  const state = loadState()
  const id = 'CERT-' + new Date().getFullYear() + '-' + Math.floor(100 + Math.random() * 900)
  const date = new Date().toISOString().slice(0, 10)
  const cert = { id, business, material, weightKg, date }
  state.certificates.push(cert)
  saveState(state)
  return cert
}

export function downloadCertificate(cert: Certificate) {
  const content = `Certificate ID: ${cert.id}\nBusiness: ${cert.business}\nMaterial: ${cert.material}\nWeight (kg): ${cert.weightKg}\nDate: ${cert.date}\n\nThis is a demo certificate generated by the Midhori Loop demo.`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${cert.id}.txt`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export default {
  getDemoState,
  addSignupRequest,
  approveRequest,
  createCertificate,
  downloadCertificate,
}
